### ISSUE TITLE
Some memory leaks

### ISSUE THREAD

**Issue by bargalex** [barrycenter/BAMSettings#1]
Hi Barry,

Thanks for a great job you do!
I consider to use your BAMSettings for one of my projects and go over your code.
Just found a few minor memory leaks:

1) you should release propertyListName and paneTitle in BAMSettings dealloc method since you make copy of strings in init methods;

2)self.tableView = [[UITableView alloc] initWithFrame:CGRectZero style:UITableViewStyleGrouped];  in viewDidLoad method leaks since tableView is retain property. By the way since you subclass UITableViewController, tableView is automatically initialized to a plain table, so you can just change its style only without reinitialization.

Thanks again,
Alex

**Comment by barrycenter** [comment]
Thanks!

"1) you should release propertyListName and paneTitle in BAMSettings dealloc method since you make copy of strings in init methods;"

Fixed. Also, a similar leak existed with stringsTable so  fixed it, too.

"2)self.tableView = [[UITableView alloc] initWithFrame:CGRectZero style:UITableViewStyleGrouped]; in viewDidLoad method leaks since tableView is retain property. By the way since you subclass UITableViewController, tableView is automatically initialized to a plain table, so you can just change its style only without reinitialization."

Fixed. Since this could potentially show up in a web search, I wanted to point out that you cannot change the style of a UITableView as it is a read only property. Instead, the init method needed to be changed to resolve this.

**Comment by bargalex** [comment]
While tableView is a read-only property you can freely change its property. This is a standrad way to customize tableView appearance...

**Comment by barrycenter** [comment]
Ok, I think there's a miscommunication here. The <i>style</i> property of UITableView is read only and cannot be changed. Per the UITableView Class Reference: "Table views can have one of two styles, UITableViewStylePlain and UITableViewStyleGrouped. When you create a UITableView instance you must specify a table style, and this style cannot be changed."

Therefore, rather than doing something like:

``` objc
self.tableView.style = UITableViewStyleGrouped;
```

which won't work. You must, instead, change the initialization of the UITableViewController, for example, like this:

``` objc
- (id)init {
    if ((self = [super initWithStyle:UITableViewStyleGrouped])) {
        // Initialization code here.
    }
    return self;
}
```

**Comment by bargalex** [comment]
OK, got it. So you are completely right!

Thanks,
Alex
